listening_addr = "10.94.204.1:8080"
peer_addr= "192.168.1.1:80"    
app_socket="/tmp/db"
pause_duration = 2000
default_role = "master"

[[log_sources]]
name="test"
addr = "192.168.30.130"
port= 1433
username= "admin"
pass= "123456"
query= "select * from test;"