listening_addr = "10.235.20.1:8080"
peer_addr= "10.235.20.20:8080"    
app_socket="/tmp/db"
ping_duration = 2000
default_role = "master"
log_server = "127.0.0.1:10100"

[[log_sources]]
name="test"
addr = "192.168.77.129"
port= 1433
username= "test"
pass= "123"
query= "select * FROM [test].[dbo].[identity] where id>??"
counter_field = "id"
counter_default_value = "0"
log_server = "127.0.0.1:10200&127.0.0.2:10100"
pause_duration = 2000

