listening_addr = "10.235.20.1:8080"
peer_addr= "10.235.20.20:8080"    
app_socket="/tmp/db"
pause_duration = 2000
default_role = "master"
log_server = "127.0.0.1:1010"

[[log_sources]]
name="test"
addr = "192.168.77.129"
port= 1433
username= "test"
pass= "123"
query= "select * FROM [test].[dbo].[identity] where id>??"
counter_field = "id"
counter_default_value = "0"

[[log_sources]]
name="amir"
addr = "127.0.0.1"
port= 1433
username= "sa"
pass= "123"
query= "select * FROM [test].[dbo].[family]"
counter_field = "id"
counter_default_value = "1"


[[comp]]
result="comp1, comp2,comp3"
[[comp.log_sources]]
name="amir"
addr = "127.0.0.1"
port= 1433
username= "sa"
pass= "123"
query= "select * FROM [test].[dbo].[family]"
counter_field = "id"
counter_default_value = "1"
[[comp.log_sources]]
name="test"
addr = "127.0.0.1"
port= 1433
username= "sa"
pass= "P@ssw0rd"
query= "select * FROM [test].[dbo].[family]"
counter_field = "id"
counter_default_value = "1"